package twistwrap;

public class dxfHeaders {
    
  // start attributes
    public String dxf = "";
    public String dxfxmax = "10";
    public String dxfymax = "10";
    public String dimasz = "5.5";
    public String dimtxt = "7.1";
    public String dimexe = "2.2";
    public String lunits = "2";
    public String luprec = "4";
    public String dimdec = "9";
    public String dimzin = "8";
    public String dimexo = "0.1";
    public String dimgap = "0.1";
    
    public String cr = "\r\n";
    // end attributes
    
    // start methods
    public String dxf_header12_SimpleArtios() {
      // DXF Version 12 Header - Simplified version
     // String cr = "\r\n";
      
      dxf +="  0"+ cr;
      dxf +="SECTION"+ cr;
      dxf +="  2"+ cr;
      dxf +="HEADER"+ cr;
      dxf +="  9"+ cr;
      dxf +="$ACADVER"+ cr;
      dxf +="  1"+ cr;
      dxf +="AC1009"+ cr; // DXF Version 12
      dxf +="  9"+ cr;
      dxf +="$EXTMIN"+ cr; // X, Y, and Z drawing extents 10, 20, 30 lower-left corner (in WCS)
      dxf +=" 10"+ cr;
      dxf +="0"+ cr;
      dxf +=" 20"+ cr;
      dxf +="0"+ cr;
      dxf +="  9"+ cr;
      dxf +="$EXTMAX"+ cr; // X, Y, and Z drawing extents 10, 20, 30 upper-right corner (in WCS)
      dxf +=" 10"+ cr;
      dxf += dxfxmax + cr;
      dxf +=" 20"+ cr;
      dxf += dxfymax + cr;
      dxf +="  0"+ cr;
      dxf +="ENDSEC"+ cr;
      dxf +="  0"+ cr;
      dxf +="SECTION"+ cr;
      dxf +="  2"+ cr;
      dxf +="TABLES"+ cr;
      dxf +="  0"+ cr;
      dxf +="TABLE"+ cr;
      dxf +="  2"+ cr;
      dxf +="LAYER"+ cr;
      dxf +=" 70"+ cr;
      dxf +=" 1"+ cr;
      dxf +="  0"+ cr;
      dxf +="LAYER"+ cr;
      dxf +="  2"+ cr;
      dxf +="Design"+ cr;
      dxf +=" 70"+ cr;
      dxf +="64"+ cr;
      dxf +=" 62"+ cr;
      dxf +="7"+ cr;
      dxf +="  6"+ cr;
      dxf +="CONTINUOUS"+ cr;
      dxf +="  0"+ cr;
      dxf +="ENDTAB"+ cr;
      dxf +="  0"+ cr;
      dxf +="ENDSEC"+ cr;
      dxf +="  0"+ cr;
      dxf +="SECTION"+ cr;
      dxf +="  2"+ cr;
      dxf +="BLOCKS"+ cr;
      dxf +="  0"+ cr;
      dxf +="ENDSEC"+ cr;
      dxf +="  0"+ cr;
      dxf +="SECTION"+ cr;
      dxf +="  2"+ cr;
      dxf +="ENTITIES"+ cr;
      
      return dxf;
    } // dxf_header12_SimpleArtios
    
    public void dxf_header12_Std() // pass var by ref
  {
    // DXF Version 12 Header
  
    this.dxf +="  0" + cr;
    this.dxf +="SECTION" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="HEADER" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$ACADVER" + cr;
    this.dxf +="  1" + cr;
    this.dxf +="AC1009" + cr; // DXF Version 12
    this.dxf +="  9" + cr;
    this.dxf +="$DWGCODEPAGE" + cr;
    this.dxf +="  3" + cr;
    this.dxf +="ansi_1252" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$INSBASE" + cr;
    this.dxf +=" 10" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 20" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 30" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$EXTMIN" + cr; // X, Y, and Z drawing extents 10, 20, 30 lower-left corner (in WCS)
    this.dxf +=" 10" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 20" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 30" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$EXTMAX" + cr; // X, Y, and Z drawing extents 10, 20, 30 upper-right corner (in WCS)
    this.dxf +=" 10" + cr;
    this.dxf +=this.dxfxmax + cr;
    this.dxf +=" 20" + cr;
    this.dxf +=this.dxfymax + cr;
    this.dxf +=" 30" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$LIMMIN" + cr; // 10, 20 XY drawing limits lower-left corner (in WCS)
    this.dxf +=" 10" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 20" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$LIMMAX" + cr; // 10, 20 XY drawing limits upper-right corner (in WCS)
    this.dxf +=" 10" + cr;
    this.dxf +=this.dxfxmax + cr;
    this.dxf +=" 20" + cr;
    this.dxf +=this.dxfymax + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$ORTHOMODE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$REGENMODE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$FILLMODE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$QTEXTMODE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$MIRRTEXT" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DRAGMODE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     2" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$LTSCALE" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.5" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$OSMODE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="    37" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$ATTMODE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$TEXTSIZE" + cr; // Default text height
    this.dxf +=" 40" + cr;
    this.dxf +="1.2" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$TRACEWID" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.05" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$TEXTSTYLE" + cr;
    this.dxf +="  7" + cr;
    this.dxf +="TXT" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$CLAYER" + cr;
    this.dxf +="  8" + cr;
    this.dxf +="0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$CELTYPE" + cr;
    this.dxf +="  6" + cr;
    this.dxf +="CONTINUOUS" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$CECOLOR" + cr;
    this.dxf +=" 62" + cr;
    this.dxf +="   256" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMSCALE" + cr; // Overall dimensioning scale factor
    this.dxf +=" 40" + cr;
    this.dxf +="1.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMASZ" + cr; // Dim Arrow Size
    this.dxf +=" 40" + cr;
    this.dxf +=this.dimasz + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMEXO" + cr; // Extension line offset
    this.dxf +=" 40" + cr;
    this.dxf +=this.dimexo + cr; // Distance witness line is above drawing line
    this.dxf +="  9" + cr;
    this.dxf +="$DIMDLI" + cr; // Dimension line increment
    this.dxf +=" 40" + cr;
    this.dxf +="1.28" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMRND" + cr; // Rounding value for dimension distances
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMDLE" + cr; // Dimension line extension
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMEXE" + cr; // Extension line extension
    this.dxf +=" 40" + cr;
    this.dxf +=this.dimexe + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMTP" + cr; // Plus tolerance
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMTM" + cr; // Minus tolerance
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMTXT" + cr; // Dimensioning text height  - Not working?
    this.dxf +=" 40" + cr;
    this.dxf +=this.dimasz + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMCEN" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.09" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMTSZ" + cr; // Dimensioning tick size: 0 = no ticks
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMTOL" + cr; // Dimension tolerances generated if nonzero
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMLIM" + cr; // Dimension limits generated if nonzero
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMTIH" + cr; // Text inside horizontal if nonzero
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMTOH" + cr; // Force text inside extensions if nonzero
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMSE1" + cr; // First extension line suppressed if nonzero
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMSE2" + cr; // Second extension line suppressed if nonzero
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMTAD" + cr; // Text above dimension line if nonzero
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMZIN" + cr; // Zero suppression for "feet & inch" dimensions
    this.dxf +=" 70" + cr;
    this.dxf +="     8" + cr; // 8 = Suppress - THIS VALUE USED BY ICAD ***
    this.dxf +="  9" + cr;
    this.dxf +="$DIMBLK" + cr; // Arrow block name
    this.dxf +="  1" + cr;
    this.dxf +="" + cr; // "\"\"" + cr; The Inch Suffix?
    this.dxf +="  9" + cr;
    this.dxf +="$DIMASO" + cr; // 1 = create associative dimensioning, 0 = draw individual entities
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMSHO" + cr; // 1 = Recompute dimensions while dragging, 0 = drag original image
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMPOST" + cr; // General dimensioning suffix
    this.dxf +="  0" + cr; // 1
    this.dxf +="\"\"" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMAPOST" + cr; // Alternate dimensioning suffix
    this.dxf +="  0" + cr; // 1
    this.dxf +="\"\"" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMALT" + cr; // Alternate unit dimensioning performed if nonzero
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMALTD" + cr; // Alternate unit decimal places
    this.dxf +=" 70" + cr;
    this.dxf +="     2" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMALTF" + cr; // Alternate unit scale factor
    this.dxf +=" 40" + cr;
    this.dxf +="25.4" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMLFAC" + cr; // Linear measurements scale factor
    this.dxf +=" 40" + cr;
    this.dxf +="1.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMTOFL" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMTVP" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMTIX" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMSOXD" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMSAH" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMBLK1" + cr;
    this.dxf +="  1" + cr;
    this.dxf +="" + cr; // "\"\"" + cr; The Inch Suffix?
    this.dxf +="  9" + cr;
    this.dxf +="$DIMBLK2" + cr;
    this.dxf +="  1" + cr;
    this.dxf +="" + cr; // "\"\"" + cr; The Inch Suffix?
    this.dxf +="  9" + cr;
    this.dxf +="$DIMSTYLE" + cr; // Dimension  Style
    this.dxf +="  2" + cr;
    this.dxf +="STANDARD" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMCLRD" + cr; // DIMCLRD  Dimension line color, range is 0 = BYBLOCK, 256 = BYLAYER
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMCLRE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMCLRT" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMTFAC" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="1.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$DIMGAP" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +=this.dimgap + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$LUNITS" + cr; // Units format for coordinates & distances: 2 signifies that linear units are decimal format
    this.dxf +=" 70" + cr;
    this.dxf +=this.lunits + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$LUPREC" + cr; // Units precision for coordinates and distances
    this.dxf +=" 70" + cr;
    this.dxf +=this.luprec + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$SKETCHINC" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.1" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$FILLETRAD" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$AUNITS" + cr; // 1 for AUNITS signifies that angular units are in deg/min/sec format.
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$AUPREC" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$MENU" + cr;
    this.dxf +="  1" + cr;
    this.dxf +="." + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$ELEVATION" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$PELEVATION" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$THICKNESS" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$LIMCHECK" + cr; // Nonzero if limits checking is on
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$CHAMFERA" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$CHAMFERB" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$SKPOLY" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$TDCREATE" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="2453353.717125822" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$TDUPDATE" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="2451870.743287025" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$TDINDWG" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0234374884" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$TDUSRTIMER" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0234143287" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$USRTIMER" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$ANGBASE" + cr;
    this.dxf +=" 50" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$ANGDIR" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$PDMODE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$PDSIZE" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$PLINEWID" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$COORDS" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$SPLFRAME" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$SPLINETYPE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     6" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$SPLINESEGS" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     8" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$ATTDIA" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$ATTREQ" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$HANDLING" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$HANDSEED" + cr;
    this.dxf +="  5" + cr;
    this.dxf +="114F" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$SURFTAB1" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     6" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$SURFTAB2" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     6" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$SURFTYPE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     6" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$SURFU" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     6" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$SURFV" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     6" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$UCSNAME" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="\"\"" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$UCSORG" + cr;
    this.dxf +=" 10" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 20" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 30" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$UCSXDIR" + cr;
    this.dxf +=" 10" + cr;
    this.dxf +="1.0" + cr;
    this.dxf +=" 20" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 30" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$UCSYDIR" + cr;
    this.dxf +=" 10" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 20" + cr;
    this.dxf +="1.0" + cr;
    this.dxf +=" 30" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$PUCSNAME" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="\"\"" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$PUCSORG" + cr;
    this.dxf +=" 10" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 20" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 30" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$PUCSXDIR" + cr;
    this.dxf +=" 10" + cr;
    this.dxf +="1.0" + cr;
    this.dxf +=" 20" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 30" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$PUCSYDIR" + cr;
    this.dxf +=" 10" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 20" + cr;
    this.dxf +="1.0" + cr;
    this.dxf +=" 30" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$USERI1" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$USERI2" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$USERI3" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$USERI4" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$USERI5" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$USERR1" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$USERR2" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$USERR3" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$USERR4" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$USERR5" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$WORLDVIEW" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$SHADEDGE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     3" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$SHADEDIF" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="    70" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$TILEMODE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$MAXACTVP" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="    16" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$PLIMCHECK" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$PEXTMIN" + cr;
    this.dxf +=" 10" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 20" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 30" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$PEXTMAX" + cr;
    this.dxf +=" 10" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 20" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 30" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$PLIMMIN" + cr;
    this.dxf +=" 10" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 20" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$PLIMMAX" + cr;
    this.dxf +=" 10" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 20" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$UNITMODE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$VISRETAIN" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$PLINEGEN" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  9" + cr;
    this.dxf +="$PSLTSCALE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="ENDSEC" + cr;
    this.dxf +="  0" + cr;
  
    this.dxf +="SECTION" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="TABLES" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="TABLE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="VPORT" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="VPORT" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="*ACTIVE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +=" 10" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 20" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 11" + cr;
    this.dxf +="1.0" + cr;
    this.dxf +=" 21" + cr;
    this.dxf +="1.0" + cr;
    this.dxf +=" 12" + cr;
    this.dxf +="491.6758826665903" + cr;
    this.dxf +=" 22" + cr;
    this.dxf +="144.5710233859099" + cr;
    this.dxf +=" 13" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 23" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 14" + cr;
    this.dxf +="1.0" + cr;
    this.dxf +=" 24" + cr;
    this.dxf +="1.0" + cr;
    this.dxf +=" 15" + cr;
    this.dxf +="0.5" + cr;
    this.dxf +=" 25" + cr;
    this.dxf +="0.5" + cr;
    this.dxf +=" 16" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 26" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 36" + cr;
    this.dxf +="1.0" + cr;
    this.dxf +=" 17" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 27" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 37" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="501.9848877072563" + cr;
    this.dxf +=" 41" + cr;
    this.dxf +="1.830909" + cr;
    this.dxf +=" 42" + cr;
    this.dxf +="50.0" + cr;
    this.dxf +=" 43" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 44" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 50" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 51" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 71" + cr;
    this.dxf +="    16" + cr;
    this.dxf +=" 72" + cr;
    this.dxf +="   100" + cr;
    this.dxf +=" 73" + cr;
    this.dxf +="     1" + cr;
    this.dxf +=" 74" + cr;
    this.dxf +="     1" + cr;
    this.dxf +=" 75" + cr;
    this.dxf +="     0" + cr;
    this.dxf +=" 76" + cr;
    this.dxf +="     0" + cr;
    this.dxf +=" 77" + cr;
    this.dxf +="     0" + cr;
    this.dxf +=" 78" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="ENDTAB" + cr;
    this.dxf +="  0" + cr;
  
    this.dxf +="TABLE" + cr; // Line Types
    this.dxf +="  2" + cr;
    this.dxf +="LTYPE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="    10" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="LTYPE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="CONTINUOUS" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  3" + cr;
    this.dxf +="Solid line" + cr;
    this.dxf +=" 72" + cr;
    this.dxf +="    65" + cr;
    this.dxf +=" 73" + cr;
    this.dxf +="     0" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="LTYPE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="DASHED" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  3" + cr;
    this.dxf +="__ __ __ __ __ __ __ __ __ __ __ __ __ __ __" + cr;
    this.dxf +=" 72" + cr;
    this.dxf +="    65" + cr;
    this.dxf +=" 73" + cr;
    this.dxf +="     2" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.75" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="0.5" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="-0.25" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="LTYPE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="HIDDEN" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  3" + cr;
    this.dxf +="_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ " + cr;
    this.dxf +=" 72" + cr;
    this.dxf +="    65" + cr;
    this.dxf +=" 73" + cr;
    this.dxf +="     2" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.375" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="0.25" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="-0.125" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="LTYPE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="CENTRE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  3" + cr;
    this.dxf +="____ _ ____ _ ____ _ ____ _ ____ _ ____ _ __" + cr;
    this.dxf +=" 72" + cr;
    this.dxf +="    65" + cr;
    this.dxf +=" 73" + cr;
    this.dxf +="     4" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="2.0" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="1.25" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="-0.25" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="0.25" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="-0.25" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="LTYPE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="PHANTOM" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  3" + cr;
    this.dxf +="_____ _ _ _____ _ _ _____ _ _ _____ _ _ ____" + cr;
    this.dxf +=" 72" + cr;
    this.dxf +="    65" + cr;
    this.dxf +=" 73" + cr;
    this.dxf +="     6" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="2.5" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="1.25" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="-0.25" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="0.25" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="-0.25" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="0.25" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="-0.25" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="LTYPE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="DOT" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  3" + cr;
    this.dxf +="............................................" + cr;
    this.dxf +=" 72" + cr;
    this.dxf +="    65" + cr;
    this.dxf +=" 73" + cr;
    this.dxf +="     2" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.25" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="-0.25" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="LTYPE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="DASHDOT" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  3" + cr;
    this.dxf +="__ . __ . __ . __ . __ . __ . __ . __ . __ ." + cr;
    this.dxf +=" 72" + cr;
    this.dxf +="    65" + cr;
    this.dxf +=" 73" + cr;
    this.dxf +="     4" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="1.0" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="0.5" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="-0.25" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="-0.25" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="LTYPE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="BORDER" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  3" + cr;
    this.dxf +="__ __ . __ __ . __ __ . __ __ . __ __ . __ _" + cr;
    this.dxf +=" 72" + cr;
    this.dxf +="    65" + cr;
    this.dxf +=" 73" + cr;
    this.dxf +="     6" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="1.75" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="0.5" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="-0.25" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="0.5" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="-0.25" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="-0.25" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="LTYPE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="DIVIDE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  3" + cr;
    this.dxf +="__ . . __ . . __ . . __ . . __ . . __ . . __" + cr;
    this.dxf +=" 72" + cr;
    this.dxf +="    65" + cr;
    this.dxf +=" 73" + cr;
    this.dxf +="     6" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="1.25" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="0.5" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="-0.25" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="-0.25" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="-0.25" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="LTYPE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="DOTS" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  3" + cr;
    this.dxf +="close" + cr;
    this.dxf +=" 72" + cr;
    this.dxf +="    65" + cr;
    this.dxf +=" 73" + cr;
    this.dxf +="     2" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.1" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="0.05" + cr;
    this.dxf +=" 49" + cr;
    this.dxf +="-0.05" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="ENDTAB" + cr;
    this.dxf +="  0" + cr;
  
    this.dxf +="TABLE" + cr; // *** Layers *******************************************************************
    this.dxf +="  2" + cr;
    this.dxf +="LAYER" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     7" + cr;
    this.dxf +="  0" + cr;
    
    this.dxf +="LAYER" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="0" + cr;  // **** 0 LAYER ****
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +=" 62" + cr;
    this.dxf +="     7" + cr;
    this.dxf +="  6" + cr;
    this.dxf +="CONTINUOUS" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="LAYER" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="CUT" + cr; // **** CUT LAYER ****
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +=" 62" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  6" + cr;
    this.dxf +="CONTINUOUS" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="LAYER" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="PERF" + cr; // **** PERF LAYER ****
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +=" 62" + cr;
    this.dxf +="     2" + cr;
    this.dxf +="  6" + cr;
    this.dxf +="CONTINUOUS" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="LAYER" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="CREASE" + cr; // **** CREASE LAYER ****
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +=" 62" + cr;
    this.dxf +="     3" + cr;
    this.dxf +="  6" + cr;
    this.dxf +="CONTINUOUS" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="LAYER" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="DIMS" + cr; // **** DIMS LAYER ****
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +=" 62" + cr;
    this.dxf +="     5" + cr;
    this.dxf +="  6" + cr;
    this.dxf +="CONTINUOUS" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="LAYER" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="CUTCRE" + cr; // **** CUTCRE LAYER ****
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +=" 62" + cr;
    this.dxf +="     6" + cr;
    this.dxf +="  6" + cr;
    this.dxf +="CONTINUOUS" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="LAYER" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="DEFPOINTS" + cr; // **** DefPoints LAYER ****
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr; 
    this.dxf +=" 62" + cr;
    this.dxf +="     7" + cr;
    this.dxf +="  6" + cr;
    this.dxf +="CONTINUOUS" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="ENDTAB" + cr;
    this.dxf +="  0" + cr;
  
    this.dxf +="TABLE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="STYLE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     2" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="STYLE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="STANDARD" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 41" + cr;
    this.dxf +="1.0" + cr;
    this.dxf +=" 50" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 71" + cr;
    this.dxf +="     0" + cr;
    this.dxf +=" 42" + cr;
    this.dxf +="0.2" + cr;
    this.dxf +="  3" + cr;
    this.dxf +="txt" + cr;
    this.dxf +="  4" + cr;
    this.dxf +="\"\"" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="STYLE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="TXT" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +=" 40" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 41" + cr;
    this.dxf +="1.0" + cr;
    this.dxf +=" 50" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 71" + cr;
    this.dxf +="     0" + cr;
    this.dxf +=" 42" + cr;
    this.dxf +="0.2" + cr;
    this.dxf +="  3" + cr;
    this.dxf +="txt" + cr;
    this.dxf +="  4" + cr;
    this.dxf +="\"\"" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="ENDTAB" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="TABLE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="VIEW" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="ENDTAB" + cr;
    this.dxf +="  0" + cr;
  
    this.dxf +="TABLE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="UCS" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="ENDTAB" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="TABLE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="APPID" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="APPID" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="ACAD" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="ENDTAB" + cr;
  
    this.dxf_header_DimsTable();
  
    this.dxf +="SECTION" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="BLOCKS" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="BLOCK" + cr;
    this.dxf +="  8" + cr;
    this.dxf +="0" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="$MODEL_SPACE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +=" 10" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 20" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 30" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  3" + cr;
    this.dxf +="$MODEL_SPACE" + cr;
    this.dxf +="  1" + cr;
    this.dxf +="\"\"" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="ENDBLK" + cr;
    this.dxf +="  5" + cr;
    this.dxf +="21" + cr;
    this.dxf +="  8" + cr;
    this.dxf +="0" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="BLOCK" + cr;
    this.dxf +=" 67" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  8" + cr;
    this.dxf +="0" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="$PAPER_SPACE" + cr;
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +=" 10" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 20" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +=" 30" + cr;
    this.dxf +="0.0" + cr;
    this.dxf +="  3" + cr;
    this.dxf +="$PAPER_SPACE" + cr;
    this.dxf +="  1" + cr;
    this.dxf +="\"\"" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="ENDBLK" + cr;
    this.dxf +="  5" + cr;
    this.dxf +="76" + cr;
    this.dxf +=" 67" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  8" + cr;
    this.dxf +="0" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="ENDSEC" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="SECTION" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="ENTITIES" + cr;
  
    //return null;
  } // DXF_Hearder12
  
  public void dxf_header_DimsTable() {
    
    this.dxf +="  0" + cr;
    this.dxf +="TABLE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="DIMSTYLE" + cr; // Dimension Style table
    this.dxf +=" 70" + cr;
    this.dxf +="     1" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="DIMSTYLE" + cr;
    this.dxf +="  2" + cr;
    this.dxf +="STANDARD" + cr; // dimension style name
    this.dxf +=" 70" + cr;
    this.dxf +="     0" + cr;
    this.dxf +="  0" + cr; // General dimensioning suffix  3
    this.dxf +=cr; // 
    this.dxf +="  4" + cr;
    this.dxf +=cr; // 
    this.dxf +="  5" + cr;
    this.dxf +=cr; // 
    this.dxf +="  6" + cr;
    this.dxf +=cr; // 
    this.dxf +="  7" + cr;
    this.dxf +=cr; // 
    this.dxf +=" 40" + cr;
    this.dxf +="1.0" + cr;
    this.dxf +=" 41" + cr; // dimasz Dim Arrow Size ***
    this.dxf +="5.18" + cr;
    this.dxf +=" 42" + cr;
    this.dxf +="3.0625" + cr;
    this.dxf +=" 43" + cr; // (dimdli) Dimension line increment
    this.dxf +="0.38" + cr;
    this.dxf +=" 44" + cr; // dimexe Extension line extension (Beyond the arrow line) ***
    this.dxf +="0.3" + cr;
    this.dxf +=" 45" + cr; // dimrnd
    this.dxf +="0.0" + cr;
    this.dxf +=" 46" + cr; // dimdle
    this.dxf +="0.0" + cr;
    this.dxf +=" 47" + cr; // dimtp
    this.dxf +="0.0" + cr;
    this.dxf +=" 48" + cr; // dimtm
    this.dxf +="0.0" + cr;
    this.dxf +="140" + cr; // dimtxt Dimension Text size ***
    this.dxf +="7.08" + cr;
    this.dxf +="141" + cr; // dimcen Size of center mark/lines
    this.dxf +="0.09" + cr;
    this.dxf +="142" + cr; // dimtsz
    this.dxf +="0.0" + cr;
    this.dxf +="143" + cr; // dimaltf Alternate unit scale factor
    this.dxf +="25.4" + cr;
    this.dxf +="144" + cr; // dimlfac Linear measurements scale factor
    this.dxf +="1.0" + cr;
    this.dxf +="145" + cr; // dimtvp Text vertical position
    this.dxf +="0.0" + cr;
    this.dxf +="146" + cr; // dimtfac
    this.dxf +="1.0" + cr;
    this.dxf +="147" + cr; // dimgap Dimension line gap
    this.dxf +="0.09" + cr;
    this.dxf +=" 71" + cr; // dimtol
    this.dxf +="     0" + cr;
    this.dxf +=" 72" + cr; // dimlim
    this.dxf +="     0" + cr;
    this.dxf +=" 73" + cr; // dimtih
    this.dxf +="     1" + cr;
    this.dxf +=" 74" + cr; // dimtoh
    this.dxf +="     1" + cr;
    this.dxf +=" 75" + cr; // dimse1
    this.dxf +="     0" + cr;
    this.dxf +=" 76" + cr; // dimse2
    this.dxf +="     0" + cr;
    this.dxf +=" 77" + cr; // dimtad
    this.dxf +="     0" + cr;
    this.dxf +=" 78" + cr; // DIMZIN Zero suppression for "feet & inch" dimensions
    this.dxf +="     8" + cr;
    this.dxf +="170" + cr; // dimalt
    this.dxf +="     0" + cr;
    this.dxf +="171" + cr; // dimaltd Alternate unit decimal places
    this.dxf +="     2" + cr;
    this.dxf +="172" + cr; // dimtofl
    this.dxf +="     0" + cr;
    this.dxf +="173" + cr; // dimsah
    this.dxf +="     0" + cr;
    this.dxf +="174" + cr; // dimtix
    this.dxf +="     0" + cr;
    this.dxf +="175" + cr; // dimsoxd
    this.dxf +="     0" + cr;
    this.dxf +="176" + cr; // dimclrd
    this.dxf +="     0" + cr;
    this.dxf +="177" + cr; // dimclre
    this.dxf +="     0" + cr;
    this.dxf +="178" + cr; // dimclrt
    this.dxf +="     0" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="ENDTAB" + cr;
    this.dxf +="  0" + cr;
    this.dxf +="ENDSEC" + cr;
    this.dxf +="  0" + cr;
  
    //return null;
  } // dxf_header_DimsTable



} // dxfHeaders
